server:
  port: 8080

spring:

  banner:
    location: none

  jooq:
    sql-dialect: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USERNAME}
    password: ${DB_TEST_PASSWORD}

  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    change-log: db/changelog/changelog.xml